# Try to find the AOADGT library
# AOADGT_FOUND - system has AOADGT lib
# AOADGT_INCLUDE_DIR - the AOADGT include directory
# AOADGT_LIBRARIES - Libraries needed to use AOADGT

if (AOADGT_INCLUDE_DIR AND AOADGT_LIBRARIES)
    # Already in cache, be silent
    MESSAGE(STATUS "Hello")
    set(AOADGT_FIND_QUIETLY TRUE)
endif (AOADGT_INCLUDE_DIR AND AOADGT_LIBRARIES)

FIND_PATH(AOADGT_INCLUDE_DIR NAMES AOADGT/settings.h )
FIND_LIBRARY(AOADGT_LIBRARIES NAMES aoadgt  libaoadgt AOADGT libAOADGT )
MESSAGE(STATUS "AOADGT include: " ${AOADGT_INCLUDE_DIR})
MESSAGE(STATUS "AOADGT libs: " ${AOADGT_LIBRARIES})

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(aoadgt DEFAULT_MSG AOADGT_INCLUDE_DIR AOADGT_LIBRARIES)