# Try to find the NEWCKKS library
# NEWCKKS_FOUND - system has NEWCKKS lib
# NEWCKKS_INCLUDE_DIR - the NEWCKKS include directory
# NEWCKKS_LIBRARIES - Libraries needed to use NEWCKKS

if (NEWCKKS_INCLUDE_DIR AND NEWCKKS_LIBRARIES)
    # Already in cache, be silent
    set(NEWCKKS_FIND_QUIETLY TRUE)
endif (NEWCKKS_INCLUDE_DIR AND NEWCKKS_LIBRARIES)

FIND_PATH(NEWCKKS_INCLUDE_DIR NAMES NEWCKKS/settings.h )
FIND_LIBRARY(NEWCKKS_LIBRARIES NAMES NEWCKKSckks libNEWCKKSckks )
MESSAGE(STATUS "NEWCKKS libs: " ${NEWCKKS_LIBRARIES})

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(NEWCKKS DEFAULT_MSG NEWCKKS_INCLUDE_DIR NEWCKKS_LIBRARIES)